//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fortune_Teller_MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Fortune
    {
        public int FortuneID { get; set; }
        public int CustomerID { get; set; }
        public byte YearsUntilRetirement { get; set; }
        public decimal MoneyInBank { get; set; }
        public string VacationHome { get; set; }
        public string TransportationMode { get; set; }
    
        public virtual Customer Customer { get; set; }
    }
}
